# Generated by Django 5.2.17 on 2026-10-09 01:37

import django.db.models.deletion
import django.db.models.functions.text
import oficinas.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oficinas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, validators=[oficinas.base.validar_nombre])),
                ('activo', models.BooleanField(default=True)),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tramites', to='oficinas.oficina')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
                'default_manager_name': 'objects',
                'constraints': [models.CheckConstraint(condition=models.Q(('nombre__regex', '\\S')), name='tramites_tramite_nombre_con_contenido'), models.UniqueConstraint(django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('nombre')), models.F('oficina'), name='tramites_tramite_nombre_por_oficina_unico')],
            },
        ),
    ]
