# Generated by Django 5.2.17 on 2026-10-10 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'base_manager_name': 'objects', 'default_manager_name': 'objects', 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
