# Generated by Django 5.2.17 on 2026-10-10 19:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficinas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionOperadorOficina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_operadores', to='oficinas.oficina')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_oficinas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='EventoAsignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('operacion', models.CharField(choices=[('CREACION', 'Creación'), ('REACTIVACION', 'Reactivación')], max_length=12)),
                ('activo_anterior', models.BooleanField(null=True)),
                ('activo_nuevo', models.BooleanField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_asignaciones', to=settings.AUTH_USER_MODEL)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='oficinas.asignacionoperadoroficina')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
                'default_manager_name': 'objects',
            },
        ),
        migrations.AddConstraint(
            model_name='asignacionoperadoroficina',
            constraint=models.UniqueConstraint(fields=('operador', 'oficina'), name='oficinas_asignacion_operador_oficina_unica'),
        ),
        migrations.AddConstraint(
            model_name='eventoasignacion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('activo_anterior__isnull', True), ('activo_nuevo', True), ('operacion', 'CREACION')), models.Q(('activo_anterior', False), ('activo_anterior__isnull', False), ('activo_nuevo', True), ('operacion', 'REACTIVACION')), _connector='OR'), name='oficinas_eventoasignacion_estados_coherentes'),
        ),
    ]
